site_url: https://nashme.sh
site_name: NashMesh
site_description: Connecting the Greater Nashville area over Mesh!

# Navigation
nav:
  - Home: index.md
  - Getting Started:
    # - Choosing a Device: getting-started/devices.md
    - What is MeshCore?: getting-started/platforms.md
    - MeshCore Setup: getting-started/meshcore.md
    - Meshtastic Setup: getting-started/meshtastic.md
    - Setting up MQTT: mqtt.md
  - Network Map: map.md
  - Posts: posts.md
  - Resources:
    - Potato Map: https://potato.nashme.sh
    - MeshCore Analyzer: https://analyzer.nashme.sh
  - Fundraising: fundraising.md
  - Discord:
    - Information: discord.md
    - Join Server: https://discord.gg/sSS8gEpuh8

# Theming
theme:
  name: simple-blog
  logo: static/images/logo.png
  favicon: static/images/favicon.ico
  custom_dir: overrides
  sidebar: true
  navigation_depth: 4
  theme_style: dark
  highlightjs: true
  components:
    site_name: true
    title: false
    menu: true
    preview: true
    footer: true
  colors:
    text: black
    title: black
    primary: black
    background: white

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
# Plugins
plugins:
  - search
  - macros
  - blogging:
      locale: en
      dirs:
        - posts
        - meetups
  - link-embeds:
      enabled: true
      name_default: "Untitled Link"
      desc_default: " "
      image_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/c0298d98-0910-4235-a88f-0c3e2f704ba7"
      image_disabled: false
      favicon_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/b37da9c6-6f17-4c3f-9c94-c346a6f31bfa"
      favicon_disabled: false
      favicon_size: 25
      target: "blank"
      accent: "FFFFFF1A"
      verbose: false


# Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - static/styles/statistics.css
  - https://unpkg.com/leaflet@1.9.4/dist/leaflet.css
  - static/styles/leaflet.css
  - static/styles/leaflet.markercluster.css
  - static/styles/leaflet.markercluster.default.css
  - static/styles/extra.css
  - static/styles/link-embeds.css
  - static/styles/discord.css

extra_javascript:
  - static/js/jquery.js
  - static/js/malla.js
  - static/js/custom.js
  - static/js/leaflet.js
  - static/js/heatmap.js
  - static/js/leaflet-heatmap.js
  - static/js/leaflet.markercluster.js
  - static/js/node-map.js

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/sSS8gEpuh8
      name: Join our Discord
